
version: '3.3'
services:
    nginx:
       image: nginx:1.17.6-alpine
       ports:
            - "8888:80"
       volumes:
                - .:/application
                - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
       depends_on:
                - php
                - db
                -  redis
                - phpmyadmin

    php:
        build: ./docker
        volumes:
            - .:/application
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - db
            - redis
        environment:
            - DB_PORT=3306
            - DB_HOST=db
            - DB_USERNAME=root
            - DB_PASS=
            - DB_NAME=fashion


    db:
        image: mysql:5.7.27
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=fashion
            - MYSQL_USER=root
            - MYSQL_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    redis:
        image: redis:5.0.6-alpine
        ports:
            - "6382:6379"

    phpmyadmin:
        image: phpmyadmin
        ports:
            - "8082:80"


volumes:
    db_data:
